### ISSUE TITLE
Example for node 

### ISSUE THREAD

**Issue by shaeinst** [Pcothren/DearPyGui-Examples#65]
please add example for node.
and one more question, can we change the shape of node? if yes, can you please write an example?
if not, how to make custom shaped node? i want to make simple logic gate simulation app where we can simulate logic like AND, OR and NOT

**Comment by Tremeschin** [comment]
I could get some basic understanding how it works by looking through issues with the keyword "Node" on DearPyGui's repo like [here](https://github.com/hoffstadt/DearPyGui/issues/848) and [this other one](https://github.com/hoffstadt/DearPyGui/issues/786#issuecomment-813392254).

Looks like only on version 0.7 we'll have more styling options, it's only the bare minimum implemented as of version 0.6.

IIRC I have read somewhere that as of today we are "a few weeks behind" the 0.7 release, looks like we'll have some juicy stuff to play with after the initial releases of this version like pin style, coloring how it is on the demo gif on main repo's readme.

I'm interested as well in examples, though reading the source code doesn't hurt and we can see the available arguments and experiment ourselves in the mean time (perhaps build dearpygui from master?)

**Comment by Pcothren** [comment]
building from master is always available a few people have already done it, and the instructions are shown in the [DPG wiki](https://github.com/hoffstadt/DearPyGui/wiki/Building-a-Local-Wheel)
we have been super busy putting together the latest release so im expecting that these will follow the 0.7 release which is going to be put on test py this week

the demo in the DPG repo will cover alot of things, and we will upgrade and expand the examples here to cover the new sections

**Comment by Tremeschin** [comment]
Been using dearpygui from master for a few now, I really enjoyed its internals using `@contextmanager` instead of unique naming for identifying stuff!!

Think this really helps dealing with node editor as we can just store whatever we got from entering the context, a lot easier to micro manage objects using Python vars assignment than name strings.

> the demo in the DPG repo will cover alot of things, and we will upgrade and expand the examples here to cover the new sections

Had to make some changes to the current `demo.py` to make it run, namely remove logger due missing import and to add `import dearpygui.simple as ds; show_demo(); ds.start_dearpygui()` at the end of the file, [the script as a whole](https://github.com/hoffstadt/DearPyGui/blob/fe496b3a6148ad0361bb3ee88dd111ffe3ab88e3/DearPyGui/dearpygui/demo.py#L1863) gives a good idea how stuff will work and is a nice starting point on the new architecture before proper documentation!

I can see some unpolished thing there and there but it's expected from a dev version while changing major stuff on the code, great job for you all :+1:

ᶠᶦʳˢᵗ ᵗᶦᵐᵉ ᵗʰᵃᵗ ᴵ'ᵐ ʰʸᵖᵉᵈ ᶠᵒʳ ᵃ ᵖᵃᶜᵏᵃᵍᵉ ʳᵉˡᵉᵃˢᵉ ˡᵒˡ
